now able to add filename extension

diff --git a/bin/crx b/bin/crx
--- a/bin/crx
+++ b/bin/crx
@@ -1,4 +1,31 @@
+#!/bin/bash
 thisdir=$(dirname $0)
-$thisdir/rxc $*
-$thisdir/rxas $*
-$thisdir/rxvm $*
+filename=$(basename "$1")
+path=$(dirname "$1")
+extension="${filename##*.}"
+filename="${filename%.*}"
+
+if [ $extension = $filename ]; then
+  # If the filename has no extension, check for a file with .rexx extension
+  filename_rexx="${filename}.rexx"
+  if [ ! -f "$filename_rexx" ]; then
+    echo "Error: $filename_rexx does not exist."
+    exit 1
+  fi
+  # Set extension to "rexx" if the file exists
+  extension="rexx"
+fi
+
+case "$extension" in
+  rexx) true
+       ;;
+  *)   echo "File extension is not correct. Expected .rexx file."
+       exit 1
+       ;;
+esac
+
+echo ${filename}
+$thisdir/rxc ${filename}
+$thisdir/rxas ${filename}
+$thisdir/rxvm ${filename}
+
diff --git a/bin/crxc b/bin/crxc
--- a/bin/crxc
+++ b/bin/crxc
@@ -1,11 +1,37 @@
+#!/bin/bash
 thisdir=$(dirname $0)
-rxc  $1
-rxas $1
-rxcpack $1 $thisdir/../lib/rxfns/library
-gcc -o $1 \
+filename=$(basename "$1")
+path=$(dirname "$1")
+extension="${filename##*.}"
+filename="${filename%.*}"
+
+if [ $extension = $filename ]; then
+  # If the filename has no extension, check for a file with .rexx extension
+  filename_rexx="${filename}.rexx"
+  if [ ! -f "$filename_rexx" ]; then
+    echo "Error: $filename_rexx does not exist."
+    exit 1
+  fi
+  # Set extension to "rexx" if the file exists
+  extension="rexx"
+fi
+
+case "$extension" in
+  rexx) true
+       ;;
+  *)   echo "File extension is not correct. Expected .rexx file."
+       exit 1
+       ;;
+esac
+
+
+rxc  ${filename}
+rxas ${filename}
+rxcpack ${filename} $thisdir/../lib/rxfns/library
+gcc -o ${filename} \
     -lrxvml -lmachine -lavl_tree -lplatform -lm  \
     -L$thisdir/..//interpreter \
     -L$thisdir/../machine \
     -L$thisdir/../avl_tree \
     -L$thisdir/../platform \
-    $1.c
+    ${filename}.c
diff --git a/bin/rxas b/bin/rxas
--- a/bin/rxas
+++ b/bin/rxas
@@ -1,3 +1,27 @@
-thisdir=$(dirname $0)	
-$thisdir/../assembler/rxas $*
+#!/bin/bash
+thisdir=$(dirname $0)
+filename=$(basename "$1")
+path=$(dirname "$1")
+extension="${filename##*.}"
+filename="${filename%.*}"
+
+if [ $extension = $filename ]; then
+  # If the filename has no extension, check for a file with .rxas extension
+  filename_rxas="${filename}.rxas"
+  if [ ! -f "$filename_rxas" ]; then
+    echo "Error: $filename_rxas does not exist."
+    exit 1
+  fi
+  # Set extension to "rxas" if the file exists
+  extension="rxas"
+fi
+
+case "$extension" in
+  rxas) true
+       ;;
+  *)   echo "File extension is not correct. Expected .rxas file."
+       exit 1
+       ;;
+esac
+$thisdir/../assembler/rxas ${filename}
 
diff --git a/bin/rxc b/bin/rxc
--- a/bin/rxc
+++ b/bin/rxc
@@ -1,3 +1,28 @@
+#!/bin/bash
 thisdir=$(dirname $0)
-$thisdir/../compiler/rxc -i $thisdir/../lib/rxfns/ $*
+filename=$(basename "$1")
+path=$(dirname "$1")
+extension="${filename##*.}"
+filename="${filename%.*}"
+
+if [ $extension = $filename ]; then
+  # If the filename has no extension, check for a file with .rexx extension
+  filename_rexx="${filename}.rexx"
+  if [ ! -f "$filename_rexx" ]; then
+    echo "Error: $filename_rexx does not exist."
+    exit 1
+  fi
+  # Set extension to "rexx" if the file exists
+  extension="rexx"
+fi
+
+case "$extension" in
+  rexx) true
+       ;;
+  *)   echo "File extension is not correct. Expected .rexx file."
+       exit 1
+       ;;
+esac
+
+$thisdir/../compiler/rxc -i $thisdir/../lib/rxfns/ ${filename}
 
